languaje: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: share-your-idea
  api_key:
    secure: oxTFsX8XscgSHbLL1RzzFEThFS7UICyZLWthz/wcQzjJipBfSYaD6Lc1yzxYZv0DCxEmulxeKo0G46yIw8CCrXCJ03ibdq/bYJEY1RfHVmwNQSJOygoFLD3PY5peWD33SAt+6f+gtTmgfeunjko4AvFpiRapIeuix7CzalZLJpCuUBrK03lumSmDtNAb5Jo5wtz0VSm9M5E+VjmvuXMLXX8Y+H60cPf3jGWXTmnRmvyfwl+5FwFVtgRJlJryTjoreLWAwPrVu4xZvLc1syRxjRQadfhCZAel22U2exujEmeXlPw1osA8aPSY+dgV01P5h+VDlFasdoTf8+GANx69XNpQuhJURCSNxgbFUYT9OpyQjYE6uOOuI8xfRSGCHxn+TYCsOSjYoRHaM2NqsWB5xhRToI/qvMNwTLWivtZoxBLkV/LML7CdaOE3Oupz8RIJDLxQUZS07Al1r1+4x9JPkuThE2/SDvsUcrt6mQ5IaNYOjzQIqbvA81darhacf39ZEE/L+FyT7uucVlVQNRFWaIfOmyPnV4ugU26XC4UkMv49+9n1JUgUKV5J3Cbpa7yxz5PTmlLT9fU8/GDXBetuuA0Y5+DjjJQsIShAs3Bf/rHY4ksvSEk/Qyp+1dDyS2cBKDkiA/jGd62YlefYsg9O50iZvDbWwg7XaNLSkQ9SSJs=
